# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # in_memory:
        #     memory: ~
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

      login: 
        pattern: ^/api/login
        stateless: true
        anonymous: true
        json_login:
          check_path: /api/login_check
          success_handler:          lexik_jwt_authentication.handler.authentication_success
          failure_handler:          lexik_jwt_authentication.handler.authentication_failure                 
      api:
          pattern:   ^/api
          stateless: true
          logout_on_user_change: true
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator

      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      main:
        anonymous: ~
          # activate different ways to authenticate

          # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

          # https://symfony.com/doc/current/security/form_login_setup.html
        provider: db_provider
        logout_on_user_change: true
        form_login:
          login_path: login
          check_path: login
          csrf_token_generator: security.csrf.token_manager

        logout:
          path:  logout
          target: /

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/logout , roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/workspace/new , roles: ROLE_ADMIN }
      - { path: ^/signup , roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/event , roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/* , roles: ROLE_USER }
    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER]
            ROLE_USER:  [ROLE_REGISTERED]
